trigger:
- master

parameters:
  - name: NodeJSServer
    default: 'Node JS Server'
  - name: ReactClient
    default: 'React Web Client'
  
pool:
  vmImage: ubuntu-latest

jobs:
- job: BuildNodeJSServer
  displayName: 'Build Node.js Server'
  steps:
  - script: echo Hello, Node.js Server!
    displayName: 'Run a one-line script'

  - script: |
      echo ${{ parameters.NodeJSServer }}
      echo ----------------
      echo $(Agent.BuildDirectory)
      echo $(Agent.BuildDirectory/**)
    displayName: 'Run a multi-line script'

  - script: |
      echo 11111111111111111111111111111
      echo $(Build.ArtifactStagingDirectory) - 1ASD
      echo 22222222222222222222222222222
      echo $(Pipeline.Workspace)/s   - 2
      echo 33333333333333333333333333333
      echo $(Build.SourcesDirectory)   - 3
      echo 444444444444444444444444444444
      echo $(Build.SourcesDirectory)   - 4
      echo 555555555555555555555555555
      ls -a
      echo 666666666666666666666666666
      pwd
      echo 7777777777777777777777777777
      whoami
      echo 888888888888888888888888888888
      ls /
      echo 99999999999999999999999999999
      cd ..
      echo xxxxxxxxxxxxxxxxxxxxxxxxxxxx
      ls -a
    displayName: 'Build Data'

  - script: |
      cd $(Build.SourcesDirectory)/server
      echo Running in the server directory
      npm install
      npm start
    displayName: 'Build Node.js Server'

- job: BuildReactClient
  displayName: 'Build React Client'
  steps:
  - script: echo Hello, React Client!
    displayName: 'Run a one-line script'

  - script: |
      cd $(Build.SourcesDirectory)/client
      echo Running in the client directory
      npm install
      npm run build
    displayName: 'Build React Client'
