trigger:
- master

parameters:
  - name: NodeJSServer
    default: 'Node JS Server'
  - name: ReactClient
    default: 'React Web Client'
  - name: TestUrls
    type: string
    default: "http://localhost:4000/test"
  
pool:
  vmImage: ubuntu-latest

jobs:
- job: BuildNodeJSServer
  displayName: 'Build Node.js Server'
  steps:
  - script: echo Hello, Node.js Server!
    displayName: 'Run a one-line script'

  - script: |
      echo ${{ parameters.NodeJSServer }}
    displayName: 'Run a parameter'

  - script: |
      ls -a
    displayName: 'Build Data'

  - script: |
      cd $(Build.SourcesDirectory)/server
      echo Running in the server directory
      npm install
      npm start &
      SERVER_PID=$!
      echo Server is running with PID $SERVER_PID
      # Save the PID to a file for later use
      echo $SERVER_PID > $(Pipeline.Workspace)/server.pid
    displayName: 'Start Node.js Server'

- job: BuildReactClient
  displayName: 'Build React Client'
  dependsOn: BuildNodeJSServer
  steps:
  - script: echo Hello, React Client!
    displayName: 'Run a one-line script'

  - script: |
      cd $(Build.SourcesDirectory)/client
      echo Running in the client directory
      npm install
      npm run build
    displayName: 'Build React Client'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/client/build'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/client-build'
    displayName: 'Copy React Client Build to Artifact Staging Directory'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/client-build'
      ArtifactName: 'ReactClientBuild'
    displayName: 'Publish React Client Build Artifacts'


