trigger:
- master

parameters:
  - name: NodeJSServer
    default: 'Node JS Server'
  - name: ReactClient
    default: 'React Web Client'
  
pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world! 
  displayName: 'Run a one-line script'

- script: |
    echo ${{ parameters.NodeJSServer }}
    echo ----------------
    echo $(Agent.BuildDirectory)
    echo $(Agent.BuildDirectory/**)
  displayName: 'Run a multi-line script'

- script: |
    echo $(Build.ArtifactStagingDirectory) - 1ASD
    echo $(Pipeline.Workspace)/s   - 2
    echo $(Build.SourcesDirectory)   - 3
    echo $(Build.SourcesDirectory)   - 4
  displayName: Build Data